[build]
builder = "nixpacks"
buildCommand = "npm run build --workspace=@evadms/web"

[deploy]
startCommand = "npm run start --workspace=@evadms/web"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
